version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/seacoo

permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
