name: Admin Portal CI

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  pre_job:
    name: "Check for changes to admin portal"
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["portal/**"]'
          paths_ignore: '["**/README.md", "**/.envrc.sample", "**/.env.sample"]'
  build:
    name: "Lint and test admin portal"
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: portal
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint && Typescript checks
        run: yarn lint
      - name: Run test
        run: yarn test
